### ISSUE TITLE
How to use the mkr command in GitHub Actions on Ubuntu environment

### ISSUE THREAD

**Issue by ikesyo** [mackerelio/mkr#302]
Currently the following installation ways noted in the README both don't work:

```
curl -fsSL https://mackerel.io/assets/files/scripts/setup-apt.sh | sh
apt-get install mkr
```

nor

```
$ go get github.com/mackerelio/mkr
$ go install github.com/mackerelio/mkr
```

https://github.com/ikesyo/sandbox-mkr-github-actions/actions/runs/142371633 is the actual result.

ref: [Virtual environments for GitHub-hosted runners - GitHub Help](https://help.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners)

**Comment by astj** [comment]
@ikesyo 

Hi, thank you for report and sorry for inconvenience due to outdated documents.  I'll update README. (the docs are SO outdated that they even include CentOS 5 :scream:)

# apt

The apt repository behind the setup script uses old signing keys, therefore the repo does not work with Debian 9~ (and corresponding Ubuntu).
Using `https://mackerel.io/file/script/setup-apt-v2.sh` instead of `https://mackerel.io/assets/files/scripts/setup-apt.sh` should work.

# go

According to your logs (that really helps me debugging, thanks!), module-aware mode is not enabled in your environment.

Following process (set environmental variable and `go get`) will install the executable into `$GOBIN`.

```
$ docker run --rm -it golang:1.14-stretch
root@d1b8925e2491:/go# export GO111MODULE=on
root@d1b8925e2491:/go# go get github.com/mackerelio/mkr
go: downloading github.com/mackerelio/mkr v0.40.1
go: github.com/mackerelio/mkr upgrade => v0.40.1
(snip)
go: downloading github.com/shurcooL/sanitized_anchor_name v1.0.0
root@d1b8925e2491:/go# which mkr
/go/bin/mkr
root@d1b8925e2491:/go#
```

**Comment by ikesyo** [comment]
@astj Thanks for the reply!

About apt, `https://mackerel.io/file/script/setup-apt-v2.sh` did work. 👍 

About go, I now got another error:

```
can't load package: cannot find module providing package github.com/mackerelio/mkr: working directory is not part of a module
```

https://github.com/ikesyo/sandbox-mkr-github-actions/runs/792120352?check_suite_focus=true#step:4:53

**Comment by ikesyo** [comment]
Ah okay, `go install` is now unnecessary.  😄

https://github.com/ikesyo/sandbox-mkr-github-actions/runs/792157433?check_suite_focus=true

**Comment by astj** [comment]
@ikesyo 
Thank you again for reporting.  I'll close this issue for now, and will update README later.
